"""user and pulse table

Revision ID: 79bf0d8f84c3
Revises: 331d87e559a2
Create Date: 2020-06-10 22:02:59.579815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79bf0d8f84c3'
down_revision = '331d87e559a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=64), nullable=True),
    sa.Column('polarisation', sa.String(length=64), nullable=True),
    sa.Column('pulse_width', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_frequency'), 'experiments', ['frequency'], unique=False)
    op.create_index(op.f('ix_experiments_polarisation'), 'experiments', ['polarisation'], unique=False)
    op.create_index(op.f('ix_experiments_pulse_width'), 'experiments', ['pulse_width'], unique=False)
    op.drop_index('ix_pulse_frequency', table_name='pulse')
    op.create_index(op.f('ix_pulse_frequency'), 'pulse', ['frequency'], unique=False)
    op.drop_index('ix_pulse_polarisation', table_name='pulse')
    op.create_index(op.f('ix_pulse_polarisation'), 'pulse', ['polarisation'], unique=False)
    op.drop_index('ix_pulse_pulse_width', table_name='pulse')
    op.create_index(op.f('ix_pulse_pulse_width'), 'pulse', ['pulse_width'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pulse_pulse_width'), table_name='pulse')
    op.create_index('ix_pulse_pulse_width', 'pulse', ['pulse_width'], unique=1)
    op.drop_index(op.f('ix_pulse_polarisation'), table_name='pulse')
    op.create_index('ix_pulse_polarisation', 'pulse', ['polarisation'], unique=1)
    op.drop_index(op.f('ix_pulse_frequency'), table_name='pulse')
    op.create_index('ix_pulse_frequency', 'pulse', ['frequency'], unique=1)
    op.drop_index(op.f('ix_experiments_pulse_width'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_polarisation'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_frequency'), table_name='experiments')
    op.drop_table('experiments')
    # ### end Alembic commands ###
